### PR TITLE
WIP: Add some initial functions for wrapping the priv- and pubkey

### PR DESCRIPTION
**Pull request by stefanberger**
Add some initial functions for wrapping the privkey and pubkey
types.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

### CODE REVIEW

**Comment by stefanberger** [comment]
This is something I am currently working to support pkcs11 in[ jwcrypto](https://github.com/latchset/jwcrypto), even though this may not be the right approach.

I have a test case for creating an RSA key pair and using the private key for signing and verifying the signature using the public key. Besides that I am using it to sign with the TPM using the PKCS#11 like support in GnuTLS.

There are currently some memory leaks in functions where the GnuTLS library is allocating memory for a gnutls_datum_t. I have marked the functions but do not know how to resolve the issue by calling gnutls_free() on the appropriate data - I get segfaults. Any hints on how to fix this?

**Comment by stefanberger** [comment]
@danpascu Any comments on these patches?

**Comment by stefanberger** [comment]
@danpascu Also works with cygwin now... Any comments? Please.

**Comment by danpascu** [comment]
I do not know anything about pcks11 to be able to give an informed opinion. What I do know is that I don't want python-gnutls to depend on twisted or to add C extension modules to it. I used ctypes, to avoid writing C extension modules.

What I also know is that I do not want to turn python-gnutls into a cryptography library. There are better cryptography libraries for python out there already, maintained by people that are more knowledgeable in the field and with more man power to maintain them in the fast changing field of cryptography than I am.
There are also plenty bad implementations with bad/insecure defaults which show that maintaining a good cryptography implementation is hard and time consuming.

For me python-gnutls started from the need to make TLS connections where both endpoints would verify each other using X509 ceritifcates, something that was not possible at the time using twisted or the standard ssl library from python, and I have little desire or need to turn it into anything more than that.

**Comment by stefanberger** [comment]
That `work` branch does work fine on an Apple Mac. `./setup.py build` builds the C module quite nicely on all three platforms.

**Comment by danpascu** [comment]
I do not mind adding the necessary wrappers for the low level C functions in gnutls/library/... so they can be used by someone interested in that functionality. What I do not want is to turn python-gnutls into a cryptographic library. In other words, exposing more of the low level C functions from gnutls is not a problem but adding high level interfaces for cryptography is because I do not want to maintain such code. It is not my aim to have python-gnutls be a cryptographic library because of the reasons I explained before.

So if I add those to gnutls/library/... can you use that to write the higher level classes that deal with pkcs11 in your code instead of adding them to python-gnutls?

**Comment by stefanberger** [comment]
@danpascu That would probably work. I was following existing pattern. The maintainance burden should be low with the tests that I added and you could request new/extension of tests if someone wanted to extend the classes. 

What do you think about the automated tests? Of course the whole test suite disappears if we get rid of the extensions in gnutls/crypto.py and this then makes the automated tests also useless except for the flake8 runs...

**Comment by stefanberger** [comment]
@danpascu I would prepare another PR with a different set of patches derived from this set here. What I need from python-gnutls is a way to access the pkcs11 functions and python 3 support. Though only those two items will require quite a few patches pulling in the C module support etc. For this I could move the wrapping classes for RSA (and DSA) keys into a test case or leave them out entirely. Do you have any comment on the Travis integration and test cases in general?

**Comment by stefanberger** [comment]
@saghul @danpascu Any comments to the above? Is there any way we can make progress on this ?

**Comment by danpascu** [comment]
This PR started as a request for adding pkcs11 support, but now is a mishmash of multiple different topics: pkcs11, crypto extensions, python3 and unit testing.

As I already said I'm not interested in adding any crypto support past the X509 needed to establish TLS connections.

Python3 support is fine but not with the loss of functionality. Validating data passed down into C is vital to prevent crashes. Also I do not want any C extension module. I used ctypes exactly to avoid that.

As for travis integration, I do not care. The project is maintained elsewhere and github is just a mirror for us.

**Comment by hughsie** [comment]
Hi @stefanberger -- I wanted to let you know I've forked python-gnutls and included your patches there. The new https://github.com/hughsie/PyGnuTLS is under the same licence as before (LGPLv2+) of course, but it's now Python 3 only. I'm reviewing pull requests so if you are using a private fork with your changes it would be great to merge them back into a common codebase. I'm planning to clean up the fork some more and then submit it to PyPI when API stable. Comments welcome!

**Comment by stefanberger** [comment]
My biggest concern would now be the TPM 1.2 related stuff, which I would not want to hold my hand into the fire for. I think I would disable/remove it.

**Pull request closed without merging**
